version: 0.1
log:
  level: info

storage:
  filesystem:
    rootdirectory: /var/lib/registry

http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]

# 启用代理模式，自动从 Docker Hub 下载并缓存镜像
proxy:
  remoteurl: https://registry-1.docker.io
